; gpi_send.conf
;
; This is the configuration file for gpi_send(1).
;
[Global]
;ChipDevice=/dev/gpiochip0
;EdgeTrigger=rising
;DebouncePeriod=1000
DestinationAddress=127.0.0.1
DestinationPort=1234

[Button1]
Offset=23
Command=Line1

[Button2]
Offset=24
Command=Line2

[Button3]
Offset=25
Command=Line3
