[Source0]
Name=Rivendell
Type=5
DefaultElement0=
DefaultElement1=
DefaultElement2=
DefaultElement3=
DefaultElement4=Rivendell Radio Automation
DefaultElement5=
DefaultElement6=
DefaultElement7=
DefaultElement8=
DefaultElement9=
DefaultElement10=
DefaultElement11=
DefaultElement12=
DefaultElement13=
DefaultElement14=
DefaultElement15=
DefaultElement16=
DefaultElement17=
DefaultElement18=
DefaultElement19=
DefaultElement20=
DefaultElement21=
DefaultElement22=
DefaultElement23=
DefaultElement24=
DefaultElement25=
DefaultElement26=
DefaultElement27=
DefaultElement28=
ConnectionType=3
ConnectionName=
ConnectionFilename=
Address=127.0.0.1
Port=34289
TtyDevice=/dev/null
TtySpeed=9600
TtyWordLength=8
TtyParity=0
TtyFlowControl=0
