; gpisend.conf
;
; This is the configuration file for gpisend(1).
;

[Global]
; The name of the device file for the GPIO device to be used.
;
;ChipDevice=/dev/gpiochip0

; Configure event triggering. The following arguments are recognized.
;    rising - Trigger an event at the beginning of a closure (default).
;   falling - Trigger an event at the end of a closure.
;      both - Trigger events at both the beginning and end of a closure.
;
;EdgeTrigger=rising

; Set the debounce interval. Argument is in microseconds.
;
;DebouncePeriod=1000

; Set inputs to be considered active when in a 'low' state.
;
;ActiveLow=Yes

; Configure input line bias. The following arguments are recognized.
;   pull-up - Bias to a 'high' state (default).
; pull-down - Bias to a 'low' state.
;  disabled - Bias not applied.
;
;LineBias=pull-up

; Set the default IP address to which to send event commands. This can be
; overrriden on a per-button basis by providing the appropriate
; 'DestinationAddress=' statement in the appropriate [Button<n>] section.
;
;DestinationAddress=127.0.0.1

; Set the default UDP port number to which to send event commands. This can be
; overrriden on a per-button basis by providing the appropriate
; 'DestinationPort=' statement in the appropriate [Button<n>] section.
;DestinationPort=1234

; Button Definitions
;
; Buttons are defined by creating '[Button<n>]' clauses, where <n> is an
; integer that begins with '1' and is incremented for each additional button.
;
; Available GPIO lines can be viewed by using the gpioscan(1) command on
; the appropriate device entry --e.g. 'gpioscan --device=/dev/gpiochip0'.

;[Button1]
;Offset=23
;Command=Line1

;[Button2]
;Offset=24
;Command=Line2

;[Button3]
;Offset=25
;Command=Line3
